language: node_js
sudo: true
dist: trusty
node_js:
- 8

before_install:
- openssl aes-256-cbc -K $encrypted_5868224eb028_key -iv $encrypted_5868224eb028_iv
  -in id_rsa.enc -out id_rsa -d

deploy:
  skip_cleanup: true
  on:
    branch: master
    repo: aquaems/website
  provider: script
  script: bash .travis/deploy.sh
notifications:
  email: false
