language: minimal
sudo: true
dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_5868224eb028_key -iv $encrypted_5868224eb028_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d

script:
  echo "running travis..."

deploy:
  skip_cleanup: true
  on:
    branch: master
    repo: AquaEMS/website
  provider: script
  script: bash .travis/deploy.sh
notifications:
  email: false
